name: musync
description: A Simple Music App.

publish_to: "none"

version: 1.0.0+1

scripts:
  # rps is the command initiatior
  build_runner: "dart run build_runner build --delete-conflicting-outputs"
  apk_split_build: "flutter build apk --split-per-abi"
  apk_build: "flutter build apk"
  apk_bundle: "flutter build appbundle"
  fix: "dart fix --apply"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  lottie: ^2.3.2
  google_sign_in: ^6.1.0
  on_audio_query: ^2.9.0
  permission_handler: ^11.0.1
  path_provider: ^2.0.15
  font_awesome_flutter: ^10.4.0
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  just_audio: ^0.9.34
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  connectivity_plus: ^4.0.1
  dio: ^4.0.4
  dartz: ^0.10.1
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  socket_io_client: ^2.0.3+1
  palette_generator: ^0.3.3+2
  image_picker: ^1.0.2
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  mockito: ^5.4.2
  pretty_dio_logger: ^1.2.0-beta-1

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/splash_screen/
    - assets/lottie/

  # fonts:
  #   - family: Sans
  #     fonts:
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-ExtraBoldItalic.ttf
  #         weight: 800
  #         style: italic
  #       - asset: assets/fonts/OpenSans_SemiCondensed/OpenSans_SemiCondensed-Bold.ttf
  #         weight: 700
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-Italic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-LightItalic.ttf
  #         weight: 200
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-Medium.ttf
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-MediumItalic.ttf
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-Regular.ttf
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-SemiBold.ttf
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-SemiBoldItalic.ttf
  #         style: italic
