name: musync
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.3.2
  http: ^0.13.6
  connectivity: ^3.0.6
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.0
  on_audio_query: ^2.9.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  font_awesome_flutter: ^10.4.0
  shimmer: ^2.0.0
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/splash_screen/
    - assets/lottie/

  # fonts:
  #   - family: Sans
  #     fonts:
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-ExtraBoldItalic.ttf
  #         weight: 800
  #         style: italic
  #       - asset: assets/fonts/OpenSans_SemiCondensed/OpenSans_SemiCondensed-Bold.ttf
  #         weight: 700
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-BoldItalic.ttf
  #         weight: 700
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-Italic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-LightItalic.ttf
  #         weight: 200
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-Medium.ttf
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-MediumItalic.ttf
  #         style: italic
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-Regular.ttf
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-SemiBold.ttf
  #       - asset: assets\fonts\OpenSans_SemiCondensed\OpenSans_SemiCondensed-SemiBoldItalic.ttf
  #         style: italic
