# name: "Android Release" # The name of the workflow
# on:
#   pull_request: # Trigger the workflow on pull requests
#     branches:
#       - main
#       - master
#     paths: # Only trigger the workflow if the following files are changed
#       - "CHANGELOGS.md"

#   push: # Trigger the workflow on push to main, master, and develop branches
#     branches:
#       - main
#       - master
#       - develop
#     paths: # Only trigger the workflow if the following files are changed
#       - "CHANGELOGS.md"

# jobs:
#   build: # Define a job named "build"
#     name: Android Build Release # Name of the job
#     runs-on: ubuntu-latest # Use ubuntu-latest as the runner

#     steps: # List of steps to perform for this job
#       # Checkout the code from the repo
#       - uses: actions/checkout@v2

#       # Setup Java environment
#       - name: Setting Java Environment
#         uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"

#       # Cache Gradle files for faster builds
#       - name: Gradle Cache
#         uses: actions/cache@v2
#         with:
#           path: |
#             ~/.gradle/caches
#             ~/.gradle/wrapper
#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#           restore-keys: |
#             ${{ runner.os }}-gradle-

#       # Setup Flutter environment
#       - name: Setting Flutter Environment
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.7.9"

#       # Install packages required for the app
#       - name: Get Packages
#         run: flutter pub get

#       # Build APK files
#       - name: Build Apk
#         run: flutter build apk --split-per-abi --build-number=${GITHUB_RUN_NUMBER}

#       # Rename the APK files for better readability
#       - name: Rename APK files
#         run: |
#           mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/Musync-v1.${{ github.run_number }}-arm64-v8a.apk
#           mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/Musync-v1.${{ github.run_number }}-armeabi-v7a.apk
#           mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/Musync-1.${{ github.run_number }}-x86_64.apk

#       # Create a Github release
#       - name: Create Release
#         uses: softprops/action-gh-release@v1
#         with:
#           tag_name: "Musync-${{ github.run_number }}" # Tag name for the release
#           name: "Musync Release ${{ github.run_number }}" # Name of the release
#           body_path: CHANGELOGS.md # Contents of the changelog file
#           files: |
#             build/app/outputs/flutter-apk/*.apk
#           draft: false
#           prerelease: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }} # GitHub token used to create the release

