name: Build and Release Flutter App

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: Automated release for commit ${{ github.sha }}
          draft: false
          prerelease: false
